<a href="https://colab.research.google.com/github/Alonsso/ipynb-notebooks/blob/main/Numpy_Taller.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Taller 



#### Importar NumPy como np

In [1]:
import numpy as np


#### Crear un arreglo de 10 ceros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crear un arreglo de 10 unos

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crear un arreglo de 10 cincos

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crear un arreglo de los números enteros desde 10 hasta 50 (incluido)

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Crear un arreglo de todos los números pares entre 10 y 50 (incluido)

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Crear una matriz de 3x3 con valores desde 0 a 8

In [10]:
arr = np.arange(0,9)
arr
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crear una matriz identidad de 3x3

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Usar NumPy para generar un número aleatorio entre 0 y 1

In [12]:
np.random.rand()

0.11498453162758193

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO
# Su resultado será diferente

array([0.13938024])

#### Usar NumPy para generar 25 números aleatorios con una distribución de probabilidad normal

In [15]:
np.random.randn(5,5)

array([[ 0.40381881,  0.49913783,  0.77154474,  0.96196776, -0.41606075],
       [-0.05819539,  0.35018939,  0.20125338, -0.60866449, -0.08449137],
       [ 0.36893055, -1.50086529, -1.21514309,  1.89270121, -0.72236979],
       [-0.40549052, -0.89941838, -1.21484059, -0.42914137, -0.16975882],
       [-0.78788939,  0.10495431, -0.60513247,  0.94408173, -0.76645586]])

In [14]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO
# Su resultado será diferente

#### Crear la siguiente matriz:

In [58]:
arr1 = np.arange(0.01,0.11, 0.01)
arr2 = np.arange(0.11,0.21, 0.01)
arr3 = np.arange(0.21,0.31, 0.01)
arr4 = np.arange(0.31,0.41, 0.01)
arr5 = np.arange(0.41,0.5, 0.01)
arr6 = np.arange(0.51,0.61, 0.01)
arr7 = np.arange(0.61,0.71, 0.01)
arr8 = np.arange(0.81,0.91, 0.01)
arr9 = np.arange(0.91,1.01, 0.01)
np.vstack((arr1,arr2,arr3,arr4,arr5,arr6,arr7,arr8,arr9))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Crear un arreglo de 20 elementos linealmente separados entre 0 y 1:

In [64]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy - Índices y Selección

A partir de la siguiente matriz, replique los resultados que se presentan a continuación:

In [65]:
a=np.arange(1,26)
h=a.reshape(5,5)
h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [76]:
h[2:, [1, 2, 3,4]]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [83]:
h[3,4]

20

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

20

In [86]:
h[:3, [1]]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[ 2],
       [ 7],
       [12]])

In [87]:
h[4]

array([21, 22, 23, 24, 25])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([21, 22, 23, 24, 25])

In [93]:
h1 = h[3,...]
h2 = h[4,...]
np.vstack((h1,h2))

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy - Operaciones

#### Obtener la suma de todos los valores de la matriz 'mat'

In [96]:
np.sum(h)

325

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

325

#### Obtener las desviación estándar de los valores en la matriz 'mat'

In [97]:
h.std()

7.211102550927978

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

7.211102550927978

#### Obtener la suma de los valores en cada columna de la matriz

In [98]:
np.apply_along_axis(sum, 0, h)

array([55, 60, 65, 70, 75])

In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([55, 60, 65, 70, 75])