<a href="https://colab.research.google.com/github/Alonsso/ipynb-notebooks/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 

**NumPy: Librería de álgebra lineal para Python.**

NumPy es el paquete fundamental para la computación científica con Python. Contiene, entre otras cosas:
* una poderoso tipo de datos de matrices N-dimensionales: arreglos numpy
* funciones sofisticadas (broadcast)
* herramientas para integrar código C/C ++ y Fortran
* funcionalidades útiles de álgebra lineal, transformada de Fourier, números aleatorios

Además de sus usos científicos obvios, NumPy también se puede usar como un contenedor multidimensional eficiente de datos genéricos. Se pueden definir tipos de datos arbitrarios. Esto permite a NumPy integrarse de manera rápida y sin problemas con una amplia variedad de bases de datos.

NumPy también es muy rápido (ya que usa librerías de lenguaje C). Para ver más información acerca de por qué usar Arreglos en lugar de Listas, ver [este post de StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).


## Instalación

**Se recomienda instalar Python usando la distribución Anaconda para asegurarse que todas las dependencias (como las librerías de álgebra lineal) se instalarán mediante el uso del comando "conda install". Si tiene Anaconda, instale NumPy simplemente escribiendo el siguiente comando en una terminal:**
    
    conda install numpy
    
**Si no tiene la distribución Anaconda, ejecute el comando "pip install numpy". Si no tiene éxito, ver: [la documentación oficial de Numpy para más instrucciones de instalación.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Una vez se haya instalado NumPy, se puede importar como una librería:

In [ ]:
import numpy as np

**En este notebook trabajaremos con:**

* Arreglos NumPy: vectores, matrices
* Funciones para generar arreglos
* Generación de arreglos con números aleatorios
* Métodos y atributos de los arreglos
* Índices en arreglos numpy
* Operaciones con arreglos
* Funciones para trabajar con arreglos


# Arreglos NumPy

Los arreglos de NumPy serán la principal funcionalidad que usaremos durante el curso. 

**Tipos de arreglos:**
* Vectores: 1-d
* Matrices: 2-d (aunque podrían tener una sola fila o una sola columna)



## Creación de Arreglos NumPy (Arrays)

### A partir de Listas de Python 

Podemos crear un Array conviertiendo una lista o lista de listas en un arreglo de NumPy:

In [ ]:
lista = [1,2,3]
lista

[1, 2, 3]

In [ ]:
np.array(lista)

array([1, 2, 3])

In [ ]:
arr = np.array(lista)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Funciones para generar arreglos

Existen varias funciones para generar Arreglos:

## arange

Funciona de forma similar al método "range" de Python pero devuelve un arreglo.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## ceros y unos (zeros/ones)

Generan arreglos de ceros (zeros) y unos (ones).

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace
Retorna un vector (arreglo de una dimensión) desde un número (primer parámetro) hasta otro (segundo parámetro) separados entre si por la misma distancia. El número de elementos está determinado por el tercer parámetro.

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

##Repaso de conceptos básicos de Álgebra Lineal
https://stanford.edu/~shervine/l/es/teaching/cs-229/repaso-algebra-lineal-calculo

## eye

Crea una matriz identidad del tamaño indicado en el argumento.

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
I = np.eye(10)

# Generación de números y arreglos de números aleatorios



Los números aleatorios son importantísimos en computación. Como veremos, NumPy ofrece funciones para generar datos aleatorios simples y basados en algunas distribuciones estadísticas.

## Crear un número aleatorio

In [ ]:
import numpy as np

# Sin argumentos se general un número aleatorio
np.random.rand()*10

6.2260005053542855

## Crear un arreglo de números aleatorios

Numpy también ofrece varias maneras de crear arreglos de número aleatorios:


### Seed
Semilla para números aleatorios 

In [ ]:
np.random.seed(10)











**texto en negrita**
### Rand

Crea un arreglo del tamaño dado y lo llena con una muestra aleatoria de números con una distribución uniforme en el rango [0, 1). 

In [ ]:
np.random.rand(4)  # Un array de 4 elementos

array([0.49850701, 0.22479665, 0.19806286, 0.76053071])

*En la distribución uniforme todos los números reales entre 0 y 1 tienen la misma probabilidad de ocurrencia.*

In [ ]:
np.random.rand(5,5) # Una matriz cuadrada 5x5 de números aleatorios

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335, 0.00394827],
       [0.51219226, 0.81262096, 0.61252607, 0.72175532, 0.29187607],
       [0.91777412, 0.71457578, 0.54254437, 0.14217005, 0.37334076],
       [0.67413362, 0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715, 0.90864888]])

In [ ]:
np.random.rand(2,4,2)

array([[[0.31923609, 0.09045935],
        [0.30070006, 0.11398436],
        [0.82868133, 0.04689632],
        [0.62628715, 0.54758616]],

       [[0.819287  , 0.19894754],
        [0.8568503 , 0.35165264],
        [0.75464769, 0.29596171],
        [0.88393648, 0.32551164]]])

### Randn
Retorna un arreglo con una muestra de números aleatorios con una distribución normal (centrada en 0), a diferencia de rand cuya distribución es uniforme:


![wget](https://drive.google.com/uc?export=view&id=1RRx5wqZeknAOTTUggdyeq0s7eOkptZDV)

In [ ]:
np.random.randn(2)

array([-0.36225179, -1.12913125])

In [ ]:
np.random.randn(4,5)

array([[-0.34971048, -1.05272652,  1.28227668, -0.17180538,  0.57765806],
       [-1.47497488,  0.07878845,  0.91841365, -0.49269736,  0.09646237],
       [-0.65275994, -0.22176244, -1.06828657, -1.22769205, -1.79857302],
       [-0.68520734, -1.40986887,  1.25239859,  0.46956276,  0.32692165]])

Más info acerca de distribuciones de probabilidad en este [**enlace**](https://www.healthknowledge.org.uk/public-health-textbook/research-methods/1b-statistical-methods/statistical-distributions). 

### Randint
Retorna números enteros aleatorios desde el primer parámetro (inclusive) hasta el segundo parámetro (excluido). Si tiene un tercer argumento, éste será el número de elementos que tendrá el arreglo de enteros aleatorios que retorna.

In [ ]:
# El primer parámetro es el límite inferior, 
# el segundo el límite superior
# el tercero es el número de elementos. Por defecto es 1
np.random.randint(1,100) 

31

In [ ]:
np.random.randint(1,100,10)

array([82, 18, 17,  1, 32, 74, 65, 39, 23, 97])

# Atributos y manipulación de los arreglos


In [ ]:
arr = np.arange(6)
ranarr = np.random.randint(0,50,10)
ranarr2 = np.random.randint(0,50,(10,10))
ranarr2

array([[26,  9, 27, 26, 48, 49, 42, 23, 25, 19],
       [48, 40, 33, 12, 11, 29, 30, 31, 28, 37],
       [15, 20, 21, 20, 35, 46, 46, 45, 30, 20],
       [20, 49, 33,  2, 33, 33, 34, 12, 44, 18],
       [46, 13,  2, 37, 31, 17, 23, 17, 33, 10],
       [15, 15, 16, 38, 49, 26,  2,  6, 33,  5],
       [ 8, 29, 48, 19, 25, 15, 35, 32, 18, 41],
       [26, 26, 10,  8, 28, 32,  7, 23,  4, 22],
       [14, 35, 20, 47, 37, 47,  3, 14, 37, 14],
       [44, 34, 21, 14, 30, 17, 38, 10, 23,  1]])

## Dimesionalidad del arreglo

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.ndim

1

In [ ]:
ranarr2.ndim

2

## Shape: Forma del arreglo

Shape  es un atributo de los arreglos que indica las dimensiones del arreglo:

In [ ]:
# Vector: 1-dimensión
arr.shape

(6,)

In [ ]:
ranarr2.shape

(10, 10)

## Reshape
Retorna un arreglo que contiene los mismos datos que el arreglo original pero con unas dimensiones nuevas.

In [ ]:
arr = arr.reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
# Debe contener el mismo número de elementos que el arreglo original. De lo contrario se produce un error como aquí:
arr.reshape(6, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## max, min, argmax, argmin

Estos métodos se usan para encontrar los valores máximos y mínimos en un arreglo. También, para encontrar los índices donde están ubicados mediante argmin/argmax.

In [ ]:
ranarr

array([32, 41, 38, 46, 48, 49, 27, 45,  0, 49])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax()

5

In [ ]:
ranarr.min()

0

In [ ]:
ranarr.argmin()

8

## dtype

También es posible averiguar el tipo de dato del arreglo usando el atributo dtype:

In [ ]:
arr.dtype

dtype('int64')

## Importar directamente función de un módulo

Para evitar tener que llamar el módulo y luego la función, por ejemplo:

**np.random **

Se puede importar la función directamente.

In [ ]:
from numpy.random import randint

In [ ]:
randint(500,1000)

558

# NumPy Indices

En un arreglo el índice es la posición de la secuencia para cada uno de los elementos.

In [ ]:
vector1 = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(vector1)
print('Elemento en posición 0: ', vector1[0])

[ 0  1  2  3  4  5  6  7  8  9 10]
Elemento en posición 0:  0


### Arreglos uni-dimesionales Vectores

La forma más sencilla de seleccionar un elemento o un conjunto de ellos de un arreglo es muy similar a las listas de Python:

In [ ]:
# Obtiene el elemento ubicado en el índice dado
vector1[8]

8

In [ ]:
# Obtiene los elementos en el rango dado (sin incluir el límite superior)
vector1[1:5]

array([1, 2, 3, 4])

In [ ]:
# Obtiene los elementos desde el inicio hasta el elemento en la posición 7
vector1[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
# Obtener desde una posición hasta el final del erreglo
print(vector1[5:])
print(vector1[5:11])

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [ ]:
# Obtener desde la posición inicial y hasta la 8, cada 2 posiciones
vector1[0:8:2]

array([0, 2, 4, 6])

In [ ]:
# Obtener la última posición del arreglo
vector1[-1]

10

In [ ]:
# Obtener todo el arreglo pero en órden inverso
vector1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Arreglos bi-dimensionales (Matrices)

In [ ]:
# Inicialización
arr2d = np.zeros((5,5))
for i in range(5):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [ ]:
matriz_a = np.array([[1,3],[2,8]])
print(matriz_a)

[[1 3]
 [2 8]]


In [ ]:
#Obtener el elemento de la primera fila y primera columna
print(matriz_a[0,0])

1


In [ ]:
#Obtener el elemento de la última fila y última columna
print(matriz_a[1][1])

8


In [ ]:
# Tamaño de la fila 1
arr_length = arr2d.shape[1]

arr_length

5

In [ ]:
#Obtener todos los elementos de la primera fila
print(matriz_a[0,:])

[1 3]


In [ ]:
#Obtener todos los elementos de la primera columna
print(matriz_a[:,0])

[1 2]


In [ ]:
# Traer la matriz 2x2 de la esquina superior izquierda
arr2d[:2,:2]

array([[0., 0.],
       [1., 1.]])

### Arreglo n-dimensionales (Tensores)


El formato general es **arr_nd[d1][d2][dn]** o **arr_2d[d1,d2,dn]**. 

Por claridad, se recomienda la notación con coma.

In [ ]:
arr_3d = np.array(([[[5,10,],[20,25]],[[7,21],[7,28]]]))
print(arr_3d)

[[[ 5 10]
  [20 25]]

 [[ 7 21]
  [ 7 28]]]


In [ ]:
# Accediendo a un elemento particular
arr_3d[0,0,0]

5

In [ ]:
# Tomar el primer elemento de la primera dimesión (Es decir una matriz)
arr_3d[0,:,:]


array([[ 5, 10],
       [20, 25]])

In [ ]:
# Traer la primera fila de las 2 submatrices
arr_3d[:,0,:]

array([[ 5, 10],
       [ 7, 21]])

In [ ]:
# Traer la última fila de las 2 submatrices
arr_3d[:,-1,:]

array([[20, 25],
       [ 7, 28]])

## Broadcasting e Indexado Elegante

### Broadcasting

Los arreglos de Numpy se diferencian de las listas de Python porque tienen la habilidad de hacer "broadcast":

In [ ]:
c = np.zeros((3, 3))
print(c)
print(c.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [ ]:
n = np.array([1, 2, 3])
print(n)
print(n.shape)

[1 2 3]
(3,)


In [ ]:
t = n + c  # Se expande la primera dimensión de n
print(t)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
arr = np.arange(1,11)
print(arr)



[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Asignar un valor dado a un rango de índices en un arreglo (Broadcasting)
arr[0:5]=100

# Resultado
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
arr[0::2]=-1

arr

array([ -1, 100,  -1, 100,  -1,   6,  -1,   8,  -1,  10])

In [ ]:
# Recuperar el arreglo anterior
arr = np.arange(0,11)

# Resultado
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Troceado de arreglos
trozo_de_arr = arr[0:6]

# Resultado
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Cambios 
trozo_de_arr[:]=99

#Show Slice again
trozo_de_arr

array([99, 99, 99, 99, 99, 99])

** OJO: los cambios también ocurren en el arreglo original!**

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

** Los datos no se copian, un "trozo" de un arreglo es simplemente una vista del arreglo original! ** Esto sirve para prevenir problemas de memoria!

In [ ]:
# Para obtener una copia, es necesario usar el método copy()
copia_arr = arr.copy()

copia_arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
copia_arr[:] = 100

copia_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### "Indexado elegante" (fancy indexing)

Se permite indexar filas o columnas enteras de una sola vez:

In [ ]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# Obtener elementos también en cualquier orden
arr[[7,3,4]]

array([17, 13, 14])

In [ ]:
# matriz
arr2d = np.zeros((10,10))

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Tamaño de la fila 1
arr_length = arr2d.shape[1]

arr_length

10

In [ ]:
# Inicialización

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
# Obtener elementos de la matriz en cualquier orden
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selección condicional


In [ ]:
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#Validación elemento a elemento
indices_cond = arr > 14
print(indices_cond)

[False False False False False  True  True  True  True  True  True]


In [ ]:
# Seleccion de elementos basados en alguna condición
arr[indices_cond]

array([15, 16, 17, 18, 19, 20])

In [ ]:
#Usando condiciones más complejas
arr[(arr>12) & (arr<18)]

array([13, 14, 15, 16, 17])

In [ ]:
x = 16
arr[arr>x]

array([17, 18, 19, 20])

# NumPy  - Operaciones


## Aritméticas

Es posible hacer operaciones aritméticas entre arreglos; y también, entre arreglos y escalares. Se usan los operadores aritméticos tradicionales.

### Operaciones con vectores

In [ ]:
v1 = np.array([2,10,10])
print(v1)

[ 2 10 10]


In [ ]:
#Multiplicación vector por escalar
print(2*v1)

[ 4 20 20]


In [ ]:
#Suma de dos vectores
v2 = np.array([1,2,1])
print(v1)
print(v2)


[ 2 10 10]
[1 2 1]


In [ ]:
# suma
print(v1+v2)

[ 3 12 11]


In [ ]:
# resta
print(v1-v2)

[1 8 9]


In [ ]:
# multiplicación
print(v1*v2)

[ 2 20 10]


In [ ]:
# división
print(v1/v2)

[ 2.  5. 10.]


In [ ]:
# Creamos arr para el siguiente ejemplo
arr = np.arange(0,10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# En Python, la siguiente división retorna un error
1/0

ZeroDivisionError: ignored

In [ ]:
# Sin embargo, en NumPy si dividimos arr/arr, obtendremos un Warning de división por cero, pero no se considera como un error! 
# Se reemplaza por 'NaN' (Not a Number)

arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# 1/arr también produce un warning, pero no un error. En la división 1/0 se obtiene 'inf' (infinito)
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
# Potencia
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### Diferencia con las listas de Python 

In [ ]:
# Listas
lista = [1, 2] 
lista2 = [3, 4]

In [ ]:
lista + lista2

[1, 2, 3, 4]

In [ ]:
lista*5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

 ### Operaciones con Matrices

#### Suma/Resta de matrices

In [ ]:
a = np.array([[1,1,1], [2,2,2]]) # arreglo 2 x 3

b = np.array([[0, 1, 2], [3, 4, 5]]) # arreglo 2 x 3

print(a)
print()
print(b)

[[1 1 1]
 [2 2 2]]

[[0 1 2]
 [3 4 5]]


In [ ]:
print(a+b)

[[1 2 3]
 [5 6 7]]


In [ ]:
print(a-b)

[[ 1  0 -1]
 [-1 -2 -3]]


#### Multiplicación de Matrices

In [ ]:
a = np.array([[1, 0], [2, -1]])
print(a)
print()
b = np.array([[1, 1], [2, 2]])
print(b)


[[ 1  0]
 [ 2 -1]]

[[1 1]
 [2 2]]


In [ ]:
# Para el producto punto se usa dot()
print(np.dot(a, b))

[[1 1]
 [0 0]]


In [ ]:
#Producto entre la misma matriz
print(np.dot(a, a))

[[1 0]
 [0 1]]


#### Multiplicación (elemento a elemento) entre matrices

In [ ]:
# El operador * multiplica los elementos uno a uno (NO es multiplicación matricial)
print(a*b)

[[ 1  0]
 [ 4 -2]]


In [ ]:
matriz_2x3 = np.ones((2,3))
print(matriz_2x3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(a/matriz_2x3)
# En Python, esta división retorna un error porque no tienen las mismas dimensiones

ValueError: ignored

### Otras operaciones


In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]]) # arreglo 2 x 3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.sum()

15

In [ ]:
a.sum(axis=1)

array([ 3, 12])

In [ ]:
a.mean(axis=1)

array([1., 4.])

In [ ]:
a.std()

1.707825127659933

# NumPy  - Funciones

* Funciones Universales
* Iterando sobre los arreglos

## Funciones Universales con Arreglos

Numpy viene con muchas [funciones universales para arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), las cuales son operaciones matemáticas que se pueden usar para efectuar una operación sobre el arreglo. Por ejemplo:

### Cálculos sobre el arreglo

In [ ]:
arr = np.array([2,6,1,10])
arr

array([ 2,  6,  1, 10])

In [ ]:
# Raíz cuadrada elemento a elemento
np.sqrt(arr)

array([1.41421356, 2.44948974, 1.        , 3.16227766])

In [ ]:
# exponencial (e^)
np.exp(arr)

array([7.38905610e+00, 4.03428793e+02, 2.71828183e+00, 2.20264658e+04])

In [ ]:
# Funciones trigonométricas
np.sin(arr)

array([ 0.90929743, -0.2794155 ,  0.84147098, -0.54402111])

In [ ]:
# Logaritmo natural
np.log(arr)

array([0.69314718, 1.79175947, 0.        , 2.30258509])

### Reducciones Básicas

In [ ]:
vector = np.random.randint(0,100,10)
print(vector)

[ 0 44 68 14  4  6 42 73 44 90]


**Máximo**

In [ ]:
np.max(vector) # igual que arr.max()

90

**Mínimo**

In [ ]:
np.min(vector)

0

**Suma de todos los elementos**

In [ ]:
np.sum(vector)

385

**Promedio**

In [ ]:
np.average(vector)

38.5

**Desviación estándar**

In [ ]:
np.std(vector)

30.19023020780067

## Iterando sobre arreglos

In [ ]:
# Arreglo 1-D
arr = np.arange(0,4)
arr

array([0, 1, 2, 3])

In [ ]:
# Iterando sobre un arreglo unidimensional
for item in arr:
    print(item)

0
1
2
3


In [ ]:
# Arreglo 2-D
arr = np.arange(0,4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [ ]:
# Iterando por filas sobre un arreglo 2-D
for fila in arr:
    print(fila)

[0 1]
[2 3]


In [ ]:
# Si se quiere hacer una operación sobre cada uno de los valores, es necesario usar la propiedad "flat"
for fila in arr.flat:
    print(fila)

0
1
2
3


In [ ]:
# Iterar sobre el par de coordenadas x,y
a = np.array([[1,2],[3,4],[5,6]])
print(a)
for index, value in np.ndenumerate(a):
  print('index:',index,', value: ',value)

[[1 2]
 [3 4]
 [5 6]]
index: (0, 0) , value:  1
index: (0, 1) , value:  2
index: (1, 0) , value:  3
index: (1, 1) , value:  4
index: (2, 0) , value:  5
index: (2, 1) , value:  6


**Consultar más info: https://docs.scipy.org/doc/numpy/user/quickstart.html**